# Generated by Django 4.1 on 2026-06-27 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("receita", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="materiais",
            name="unidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="receita.unidades"
            ),
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="nome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="receita.materiais"
            ),
        ),
    ]
