# Generated by Django 4.1 on 2026-06-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingrediente",
            old_name="nome",
            new_name="material",
        ),
        migrations.RemoveField(
            model_name="receita",
            name="ingredientes",
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="receita",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredientes",
                to="receita.receita",
            ),
        ),
        migrations.AlterField(
            model_name="materiais",
            name="unidade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receita.unidades",
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="data_cadastro",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="unidades",
            name="unidades",
            field=models.CharField(max_length=50),
        ),
    ]
