# Generated by Django 4.1 on 2026-06-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0003_rename_nome_ingrediente_material_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Materiais",
            new_name="Material",
        ),
    ]
