# Generated by Django 4.1 on 2026-06-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0004_rename_materiais_material"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Unidades",
            new_name="Unidade",
        ),
    ]
