# Generated by Django 4.1 on 2026-06-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0005_rename_unidades_unidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="unidade",
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="unidade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receita.unidade",
            ),
        ),
        migrations.AlterField(
            model_name="ingrediente",
            name="material",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receita.material",
            ),
        ),
        migrations.AlterField(
            model_name="ingrediente",
            name="receita",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingredientes",
                to="receita.receita",
            ),
        ),
    ]
