# Generated by Django 4.1 on 2026-06-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0005_rename_unidades_unidade"),
    ]

    operations = []
