# Generated by Django 4.1 on 2026-06-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0006_auto_20260627_1551"),
        ("receita", "0006_remove_material_unidade_ingrediente_unidade_and_more"),
    ]

    operations = []
