# Generated by Django 4.2.30 on 2026-07-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0007_merge_20260629_1107"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidade",
            name="simbolo",
        ),
        migrations.AlterField(
            model_name="unidade",
            name="unidades",
            field=models.CharField(max_length=60),
        ),
    ]
