# Generated by Django 4.2.30 on 2026-07-06 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("receita", "0008_remove_unidade_simbolo_alter_unidade_unidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="favoritos",
            field=models.ManyToManyField(
                blank=True,
                related_name="receitas_favoritas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
