# Generated by Django 4.1 on 2026-07-07 13:27

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0009_receita_favoritos"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="material",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("nome")
                ),
                name="material_nome_unico_case_insensitive",
            ),
        ),
        migrations.AddConstraint(
            model_name="unidade",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("unidades")
                ),
                name="unidade_nome_unico_case_insensitive",
            ),
        ),
    ]
