from django.db.models.signals import post_migrate
from django.dispatch import receiver

@receiver(post_migrate)
def popular_dados_sempre(sender, **kwargs):
    # Evita que o script rode multiplas vezes para cada app instalado
    # Substitua 'sua_app_receitas' pelo nome real da sua aplicação
    if sender.name != 'receita':
        return

    # Importamos os modelos aqui dentro para evitar problemas de carregamento do Django
    from .models import Unidade, Material
    from .utils import existe_nome_equivalente, normalizar_nome_catalogo

    # 1. Lista de Unidades
    print("Carregando unidades basicas de culinária.")
    unidades_dados = [
            "Grama",
            "Quilograma",
            "Miligrama",
            "Mililitro",
            "Litro",
            "Unidade",
            "Porção",
            "Fatia",
            "Pedaço",
            "Cubos",
            "Tiras",
            "Rodela",
            "Dente",
            "Ramo",
            "Maço",
            "Folha",
            "Pé",
            "Cabeça",
            "Gomo",
            "Banda",
            "Xícara de chá",
            "Xícara de café",
            "Copo",
            "Copo americano",
            "Taça",
            "Colher de sopa",
            "Colher de sobremesa",
            "Colher de chá",
            "Colher de café",
            "Concha",
            "Escumadeira",
            "Pitada",
            "Punhado",
            "Fio",
            "A gosto",
            "Lata",
            "Caixa",
            "Pacote",
            "Sachê",
            "Garrafa",
            "Pote",
            "Vidro",
            "Bisnaga",
            "Tablete",
            "Barra",
            "Dose",
            "Caneca",
            "Balde",
            "Forma",
            "Assadeira",
            "Quantidade suficiente para cobrir",
            "Pouco"
        ]

    for unidades in unidades_dados:
        # O get_or_create garante que só insere se não existir
        unidades = normalizar_nome_catalogo(unidades)
        status = False
        if not existe_nome_equivalente(Unidade, "unidades", unidades):
            Unidade.objects.create(unidades=unidades)
            status = True
        if status:
            print (f"unidade {unidades} Criada com sucesso")
    print ("Unidades de medida cadastrados com sucesso!")
    # 2. Lista de Materiais
    print("Carregando ingredientes basicos.")
    materiais_dados = [
            "Água",
            "Farinha de Trigo Integral",
            "Farinha de Arroz",
            "Farinha de Aveia",
            "Farinha de Centeio",
            "Farinha de Milho",
            "Farinha de Amêndoas",
            "Farinha de Coco",
            "Farinha de Grão-de-Bico",
            "Farinha de Tapioca",
            "Semolina",
            "Sêmola",
            "Amido de Milho",
            "Fécula de Batata",
            "Fécula de Mandioca",
            "Tapioca",
            "Aveia em Flocos",
            "Aveia em Flocos Finos",
            "Farelo de Aveia",
            "Arroz Branco",
            "Arroz Integral",
            "Arroz Arbóreo",
            "Arroz para Sushi",
            "Quinoa",
            "Cevada",
            "Trigo para Quibe",
            "Cuscuz de Milho",
            "Açúcar Mascavo",
            "Açúcar Demerara",
            "Açucar refinado",
            "Açucar Cristal",
            "Glicose de Milho",
            "Xarope de Bordo",
            "Melado de Cana",
            "Adoçante Culinário",
            "Stevia",
            "Xilitol",
            "Eritritol",
            "Azeite de Oliva",
            "Azeite de Dendê",
            "Óleo de Girassol",
            "Óleo de Milho",
            "Óleo de Coco",
            "Óleo de Soja",
            "Óleo de cozinha",
            "Banha Suína",
            "Margarina",
            "Manteiga",
            "Ghee",
            "Leite Integral",
            "Manteiga de garrafa",
            "Creme de leite",
            "Creme de leite vegetal",
            "Leite Desnatado",
            "Leite Semidesnatado",
            "Leite de Coco",
            "Leite de Amêndoas",
            "Leite de Aveia",
            "Iogurte Natural",
            "Iogurte Grego",
            "Requeijão",
            "Cream Cheese",
            "Ricota",
            "Muçarela",
            "Queijo Prato",
            "Queijo Parmesão",
            "Queijo Provolone",
            "Queijo Coalho",
            "Queijo Brie",
            "Queijo Camembert",
            "Queijo Gorgonzola",
            "Queijo Cheddar",
            "Queijo Suíço",
            "Queijo Gouda",
            "Queijo Cottage",
            "Mascarpone",
            "Acém",
            "Patinho",
            "Coxão Mole",
            "Coxão Duro",
            "Maminha",
            "Fraldinha",
            "Cupim",
            "Costela Bovina",
            "Filé Mignon",
            "Lagarto",
            "Músculo",
            "Peito Bovino",
            "Paleta Bovina",
            "Lombo Suíno",
            "Pernil Suíno",
            "Costela Suína",
            "Barriga Suína",
            "Bacon",
            "Linguiça Toscana",
            "Linguiça Calabresa",
            "Presunto",
            "Apresuntado",
            "Mortadela",
            "Presunto Cru",
            "Pancetta suina",
            "Peito de Frango",
            "Coxa de Frango",
            "Sobrecoxa",
            "Asa de Frango",
            "Coração de Frango",
            "Frango Inteiro",
            "Peito de Peru",
            "Peru",
            "Codorna",
            "Pato",
            "Salmão",
            "Atum",
            "Sardinha",
            "Tilápia",
            "Bacalhau",
            "Merluza",
            "Pescada",
            "Dourado",
            "Robalo",
            "Camarão",
            "Lula",
            "Polvo",
            "Mexilhão",
            "Ostra",
            "Salame",
            "Paio",
            "Chouriço",
            "Peito de peru",
            "Batata",
            "Batata Asterix",
            "Batata Inglesa",
            "Batata Baroa",
            "Mandioca",
            "Mandioca Cozida",
            "Mandioquinha",
            "Inhame",
            "Cará",
            "Cenoura",
            "Beterraba",
            "Abóbora",
            "Abobrinha",
            "Chuchu",
            "Berinjela",
            "Pepino",
            "Tomate",
            "Tomate Cereja",
            "Pimentão Verde",
            "Pimentão Vermelho",
            "Pimentão Amarelo",
            "Milho Verde",
            "Ervilha",
            "Vagem",
            "Quiabo",
            "Jiló",
            "Palmito",
            "Alface",
            "Alface Americana",
            "Alface Roxa",
            "Rúcula",
            "Agrião",
            "Espinafre",
            "Couve",
            "Couve Manteiga",
            "Couve-Flor",
            "Brócolis",
            "Repolho",
            "Repolho Roxo",
            "Acelga",
            "Almeirão",
            "Cebola",
            "Cebola Roxa",
            "Cebolinha",
            "Salsa",
            "Coentro",
            "Alho",
            "Alho-Poró",
            "Manjericão",
            "Hortelã",
            "Alecrim",
            "Tomilho",
            "Sálvia",
            "Louro",
            "Orégano Fresco",
            "Pimenta-do-Reino",
            "Pimenta Calabresa",
            "Páprica Doce",
            "Páprica Defumada",
            "Cominho",
            "Curry",
            "Noz-Moscada",
            "Canela em Pó",
            "Canela em Pau",
            "Cravo-da-Índia",
            "Erva-Doce",
            "Colorau",
            "Açafrão-da-Terra",
            "Orégano",
            "Chimichurri",
            "Tempero Baiano",
            "Vinagre Branco",
            "Vinagre de Maçã",
            "Vinagre Balsâmico",
            "Molho de Soja",
            "Molho Inglês",
            "Molho de Pimenta",
            "Ketchup",
            "Barbecue",
            "Molho de Tomate",
            "Extrato de Tomate",
            "Passata de Tomate",
            "Molho de tomate",
            "Alcaparras",
            "Azeitona Verde",
            "Azeitona Preta",
            "Picles",
            "Feijão Carioca",
            "Feijão Preto",
            "Feijão Branco",
            "Feijão Fradinho",
            "Lentilha",
            "Grão-de-Bico",
            "Ervilha Seca",
            "Soja",
            "Banana",
            "Maçã",
            "Pera",
            "Laranja",
            "Limão",
            "Limão Siciliano",
            "Tangerina",
            "Mexerica",
            "Abacaxi",
            "Manga",
            "Mamão",
            "Melancia",
            "Melão",
            "Uva",
            "Morango",
            "Framboesa",
            "Amora",
            "Mirtilo",
            "Cereja",
            "Pêssego",
            "Ameixa",
            "Kiwi",
            "Maracujá",
            "Goiaba",
            "Coco",
            "Abacate",
            "Caqui",
            "Figo",
            "Romã",
            "Caju",
            "Jabuticaba",
            "Acerola",
            "Cupuaçu",
            "Açaí",
            "Amendoim",
            "Castanha-do-Pará",
            "Castanha de Caju",
            "Nozes",
            "Amêndoas",
            "Avelã",
            "Pistache",
            "Macadâmia",
            "Pinhão",
            "Gergelim",
            "Linhaça",
            "Chia",
            "Semente de Girassol",
            "Semente de Abóbora",
            "Chocolate Meio Amargo",
            "Chocolate ao Leite",
            "Chocolate Branco",
            "Gotas de Chocolate",
            "Cacau em Pó",
            "Essência de Baunilha",
            "Extrato de Baunilha",
            "Gelatina Incolor",
            "Gelatina sem Sabor",
            "Gelatina de Morango",
            "Coco Ralado",
            "Granulado",
            "Confeitos",
            "Fermento Natural",
            "Fermento Quimico",
            "Fermento Biológico",
            "Fermento Seco",
            "Melhorador de Pão",
            "Bicarbonato de Sódio",
            "Macarrão Espaguete",
            "Macarrão Penne",
            "Macarrão Fusilli",
            "Massa de Lasanha",
            "Massa para Pastel",
            "Massa Folhada",
            "Massa para Pizza",
            "Champignon",
            "Shiitake",
            "Shimeji",
            "Funghi Secchi",
            ]

    for nome in materiais_dados:
        nome = normalizar_nome_catalogo(nome)
        status = False
        if not existe_nome_equivalente(Material, "nome", nome):
            Material.objects.create(nome=nome)
            status = True
        if status:
            print (f"Ingrediente {nome} cadastrado com com sucesso")
    print ("Ingedientes cadastrados com sucesso")
