# Generated by Django 4.1 on 2026-06-27 18:24

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_usuario_nome_grupo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="nome_grupo",
        ),
        migrations.AddField(
            model_name="grupo",
            name="administradores",
            field=models.ManyToManyField(
                related_name="familias_administradas", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="grupo",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grupo",
            name="membros",
            field=models.ManyToManyField(
                related_name="familias", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
