# Generated by Django 4.1 on 2026-06-27 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_remove_usuario_nome_grupo_grupo_administradores_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="administradores",
            field=models.ManyToManyField(
                related_name="grupos_administrados", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="membros",
            field=models.ManyToManyField(
                related_name="grupos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuarios.tipos",
            ),
        ),
    ]
