# Generated by Django 4.1 on 2026-06-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_alter_grupo_administradores_alter_grupo_membros_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tipos",
            new_name="Tipo",
        ),
    ]
