# Generated by Django 4.2.30 on 2026-07-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_rename_tipos_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="nome",
        ),
    ]
