# Generated by Django 4.2.30 on 2026-07-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0008_convitegrupo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="foto",
        ),
        migrations.AddField(
            model_name="usuario",
            name="deve_trocar_senha",
            field=models.BooleanField(default=False),
        ),
    ]
