# Generated by Django 4.2.30 on 2026-07-06 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAtividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIAR_RECEITA", "Criou a receita"),
                            ("EDITAR_RECEITA", "Editou a receita"),
                            ("EXCLUIR_RECEITA", "Excluiu a receita"),
                            ("COPIAR_RECEITA", "Copiou a receita"),
                            ("COMENTAR", "Comentou na receita"),
                            ("FAVORITAR", "Favoritou a receita"),
                            ("CRIAR_UNIDADE", "Criou a unidade"),
                            ("EDITAR_UNIDADE", "Editou a unidade"),
                            ("EXCLUIR_UNIDADE", "Excluiu a unidade"),
                            ("CRIAR_GRUPO", "Criou o grupo"),
                            ("EXCLUIR_GRUPO", "Excluiu o grupo"),
                            ("ADICIONAR_MEMBRO", "Adicionou membro ao grupo"),
                            ("REMOVER_MEMBRO", "Removeu membro do grupo"),
                            ("CADASTRAR_USUARIO", "Cadastrou-se na plataforma"),
                            ("LOGIN", "Entrou no sistema"),
                            ("LOGOUT", "Saiu do sistema"),
                            ("ALTERAR_SENHA", "Alterou a senha de acesso"),
                            ("DESFAZER_ACAO", "Reverteu uma ação do sistema"),
                        ],
                        max_length=50,
                    ),
                ),
                ("texto_jornal", models.CharField(max_length=255)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("id_objeto_alvo", models.IntegerField(blank=True, null=True)),
                ("dados_anteriores", models.JSONField(blank=True, null=True)),
                ("foi_desfeito", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_atividades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
    ]
