# Generated by Django 4.1 on 2026-07-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_remove_logatividade_foi_desfeito_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logatividade",
            name="dados_novos",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="logatividade",
            name="texto_jornal",
            field=models.TextField(),
        ),
    ]
