# Generated by Django 4.2.30 on 2026-07-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comentario",
            options={"ordering": ["-data_criacao"]},
        ),
        migrations.AddField(
            model_name="comentario",
            name="data_edicao",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
